name: custom_lint_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  change_app_package_name: ^1.1.0
  convenient_test: ^1.2.1

  cupertino_icons: ^1.0.2
  flex_color_scheme: ^6.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_native_splash: ^2.2.16
  hive: ^2.2.3
  hooks_riverpod: ^2.1.3
  mason: ^0.1.0-dev.38

dev_dependencies:
  build_verify: ^3.0.0
  convenient_test_dev: ^1.2.1
  custom_lint: ^0.2.5
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0

  melos: ^3.0.0-dev.0
  msix: ^3.7.0
  riverpod_lint: ^1.0.0
  models:
    git:
      url: https://github.com/getBoolean/flutter_boolean_template
      path: packages/models

flutter:
  uses-material-design: true
